# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Articles',
        ),
    ]
