# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171014_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Links',
        ),
    ]
